apiVersion: v1
kind: Service
metadata:
  name: loan-prediction-service
spec:
  selector:
    app: loan-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
